#!/usr/bin/env python3
"""Extract page-level INT64 FastLanes metadata from parquet_io_chunk debug logs.

What this script does:
1. Reads the run manifest generated by run_int64_snappy_page_stats.py.
2. Parses each case log for `[FL HOST META ]` and `[FL ENCODED  ]` lines.
3. Emits a canonical per-page CSV for INT64 SPLIT32 pages.

Expected input:
- --manifest-csv: usually <run_root>/03_raw/run_manifest.csv.

Primary outputs:
- --output-csv (default: sibling to manifest): page_stats_int64_fastlanes.csv.
- --machine-summary-json (optional): compact extraction stats for tooling.

Usage example:
    python3 ./tools/search/extract_fastlanes_page_stats.py \
        --manifest-csv ./artifacts/fastlanes/snappy_int64_page_stats/run_<id>/03_raw/run_manifest.csv \
        --machine-summary-json ./artifacts/fastlanes/snappy_int64_page_stats/run_<id>/02_machine/extract_summary.json
"""

from __future__ import annotations

import argparse
import csv
import json
from collections import defaultdict, deque
from pathlib import Path
from typing import Deque, Dict, List

try:
    import pyarrow.parquet as pq
except ImportError as exc:  # pragma: no cover
    raise SystemExit("PyArrow is required. Install with: pip install pyarrow") from exc


def _build_arg_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description="Extract INT64 FastLanes per-page metrics from run manifest logs"
    )
    p.add_argument("--manifest-csv", required=True, help="Path to run_manifest.csv")
    p.add_argument(
        "--output-csv",
        default="",
        help="Output page stats CSV path (default: <run_dir>/page_stats_int64_fastlanes.csv)",
    )
    p.add_argument(
        "--include-failed-cases",
        action="store_true",
        help="Also parse cases that are not marked PASS in the manifest",
    )
    p.add_argument(
        "--machine-summary-json",
        default="",
        help=(
            "Optional machine-readable extraction summary path "
            "(recommended: <run_root>/02_machine/extract_summary.json)"
        ),
    )
    return p


def _parse_kv_tokens(line: str) -> Dict[str, str]:
    out: Dict[str, str] = {}
    for token in line.strip().split():
        if "=" not in token:
            continue
        k, v = token.split("=", 1)
        out[k.strip()] = v.strip()
    return out


def _safe_int(raw: str | None, default: int = -1) -> int:
    if raw is None or raw == "":
        return default
    try:
        return int(raw)
    except ValueError:
        return default


def _load_column_names(parquet_path: Path) -> List[str]:
    pf = pq.ParquetFile(str(parquet_path))
    return [pf.schema.column(i).name for i in range(len(pf.schema))]


def _to_hex(raw: str | None) -> str:
    if raw is None:
        return ""
    value = raw.lower()
    if value.startswith("0x"):
        value = value[2:]
    if not value:
        return ""
    return "0x" + value


def _extract_from_log(
    *,
    log_file: Path,
    manifest_row: Dict[str, str],
    column_names: List[str],
) -> List[Dict[str, str]]:
    rows: List[Dict[str, str]] = []

    host_meta_by_page: Dict[int, Deque[Dict[str, str]]] = defaultdict(deque)
    chunk_page_fallback_counter: Dict[int, int] = defaultdict(int)

    num_columns = len(column_names)

    with open(log_file, "r", encoding="utf-8", errors="replace") as f:
        for line in f:
            if "[FL HOST META ]" in line:
                meta = _parse_kv_tokens(line)
                page = _safe_int(meta.get("page"), default=-1)
                if page < 0:
                    continue
                chunk_id = _safe_int(meta.get("chunk"), default=-1)
                if "chunk_page" not in meta and chunk_id >= 0:
                    meta["chunk_page"] = str(chunk_page_fallback_counter[chunk_id])
                    chunk_page_fallback_counter[chunk_id] += 1
                host_meta_by_page[page].append(meta)
                continue

            if "[FL ENCODED  ]" not in line:
                continue

            # We currently extract the INT64 SPLIT32 page lines.
            if "bw_lo=" not in line or "bw_hi=" not in line:
                continue

            encoded = _parse_kv_tokens(line)
            page = _safe_int(encoded.get("page"), default=-1)
            if page < 0:
                continue

            host = host_meta_by_page[page].popleft() if host_meta_by_page[page] else {}

            chunk_id = _safe_int(encoded.get("chunk"), default=_safe_int(host.get("chunk"), -1))
            chunk_page = _safe_int(
                encoded.get("chunk_page"), default=_safe_int(host.get("chunk_page"), -1)
            )
            if chunk_page < 0 and chunk_id >= 0:
                chunk_page = chunk_page_fallback_counter[chunk_id]
                chunk_page_fallback_counter[chunk_id] += 1

            if chunk_id >= 0 and num_columns > 0:
                row_group_index = chunk_id // num_columns
                column_index = chunk_id % num_columns
                column_name = column_names[column_index] if 0 <= column_index < num_columns else ""
            else:
                row_group_index = -1
                column_index = -1
                column_name = ""

            original_count = _safe_int(encoded.get("orig"), default=0)
            padded_count = _safe_int(encoded.get("pad"), default=0)
            body_size = _safe_int(encoded.get("body"), default=0)
            blob_size = _safe_int(encoded.get("blob"), default=0)
            header_size = _safe_int(encoded.get("hdr"), default=128)

            vector_count = padded_count // 1024 if padded_count > 0 else 0
            padding_rows = max(padded_count - original_count, 0)
            padding_pct = (padding_rows * 100.0 / original_count) if original_count > 0 else 0.0
            bytes_per_value = (body_size / float(original_count)) if original_count > 0 else 0.0

            rows.append(
                {
                    "run_id": manifest_row.get("run_id", ""),
                    "case_name": manifest_row.get("case_name", ""),
                    "input_file": manifest_row.get("input_file", ""),
                    "compression": manifest_row.get("compression", ""),
                    "encoding_map_hash": manifest_row.get("encoding_map_hash", ""),
                    "encoding_spec": manifest_row.get("encoding_spec", ""),
                    "column_name": column_name,
                    "column_index": str(column_index),
                    "row_group_index": str(row_group_index),
                    "page_index": str(chunk_page),
                    "global_page_index": str(page),
                    "chunk_id": str(chunk_id),
                    "layout_mode": encoded.get("layout", "SPLIT32"),
                    "cast_mode": encoded.get("cast", ""),
                    "original_count": str(original_count),
                    "padded_count": str(padded_count),
                    "vector_count": str(vector_count),
                    "component_bitwidth_low": str(_safe_int(encoded.get("bw_lo"), default=-1)),
                    "component_bitwidth_high": str(_safe_int(encoded.get("bw_hi"), default=-1)),
                    "min_value_low_bits_hex": _to_hex(encoded.get("min_lo")),
                    "min_value_high_bits_hex": _to_hex(encoded.get("min_hi")),
                    "body_size_bytes": str(body_size),
                    "header_size_bytes": str(header_size),
                    "blob_size_bytes": str(blob_size),
                    "encoded_bytes_per_value": f"{bytes_per_value:.8f}",
                    "padding_overhead_rows": str(padding_rows),
                    "padding_overhead_pct": f"{padding_pct:.8f}",
                    "page_start_row": str(_safe_int(host.get("start_row"), default=-1)),
                    "page_num_rows": str(_safe_int(host.get("num_rows"), default=-1)),
                    "page_num_leaf_values": str(_safe_int(host.get("num_leaf"), default=-1)),
                    "log_file": str(log_file),
                    "output_file": manifest_row.get("output_file", ""),
                }
            )

    return rows


def _write_csv(path: Path, rows: List[Dict[str, str]]) -> None:
    fields = [
        "run_id",
        "case_name",
        "input_file",
        "compression",
        "encoding_map_hash",
        "encoding_spec",
        "column_name",
        "column_index",
        "row_group_index",
        "page_index",
        "global_page_index",
        "chunk_id",
        "layout_mode",
        "cast_mode",
        "original_count",
        "padded_count",
        "vector_count",
        "component_bitwidth_low",
        "component_bitwidth_high",
        "min_value_low_bits_hex",
        "min_value_high_bits_hex",
        "body_size_bytes",
        "header_size_bytes",
        "blob_size_bytes",
        "encoded_bytes_per_value",
        "padding_overhead_rows",
        "padding_overhead_pct",
        "page_start_row",
        "page_num_rows",
        "page_num_leaf_values",
        "log_file",
        "output_file",
    ]

    with open(path, "w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)


def main() -> int:
    args = _build_arg_parser().parse_args()

    manifest_csv = Path(args.manifest_csv).expanduser().resolve()
    if not manifest_csv.exists():
        raise SystemExit(f"Manifest CSV not found: {manifest_csv}")

    output_csv = (
        Path(args.output_csv).expanduser().resolve()
        if args.output_csv
        else manifest_csv.parent / "page_stats_int64_fastlanes.csv"
    )

    with open(manifest_csv, "r", encoding="utf-8", newline="") as f:
        manifest_rows = list(csv.DictReader(f))

    all_rows: List[Dict[str, str]] = []
    per_case_counts: Dict[str, int] = {}
    skipped_cases: List[str] = []
    for row in manifest_rows:
        if row.get("status") != "PASS" and not args.include_failed_cases:
            skipped_cases.append(row.get("case_name", ""))
            continue

        log_file = Path(row.get("log_file", "")).expanduser().resolve()
        if not log_file.exists():
            print(f"WARN: log file missing, skipping case {row.get('case_name')}: {log_file}")
            skipped_cases.append(row.get("case_name", ""))
            continue

        output_file = Path(row.get("output_file", "")).expanduser().resolve()
        if not output_file.exists():
            print(
                f"WARN: output parquet missing (cannot map chunk->column), skipping {row.get('case_name')}: {output_file}"
            )
            skipped_cases.append(row.get("case_name", ""))
            continue

        column_names = _load_column_names(output_file)
        extracted = _extract_from_log(log_file=log_file, manifest_row=row, column_names=column_names)
        all_rows.extend(extracted)
        per_case_counts[row.get("case_name", "")] = len(extracted)

        print(
            f"case={row.get('case_name')} parsed_pages={len(extracted)} "
            f"log={log_file.name}"
        )

    output_csv.parent.mkdir(parents=True, exist_ok=True)
    _write_csv(output_csv, all_rows)

    if args.machine_summary_json:
        summary_path = Path(args.machine_summary_json).expanduser().resolve()
        summary_path.parent.mkdir(parents=True, exist_ok=True)
        with open(summary_path, "w", encoding="utf-8") as f:
            json.dump(
                {
                    "manifest_csv": str(manifest_csv),
                    "output_csv": str(output_csv),
                    "rows": len(all_rows),
                    "per_case_counts": per_case_counts,
                    "skipped_cases": skipped_cases,
                },
                f,
                indent=2,
            )
        print(f"Wrote machine summary JSON: {summary_path}")

    print(f"Wrote page stats CSV: {output_csv}")
    print(f"Rows: {len(all_rows)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
